#!/bin/bash

rm -rf temp
mkdir -p temp

# Build library
./build

# Copy required files
cp -r website/* temp
cp -r dist temp
cp -r examples temp

# Transpile example code to work in older browsers.
find temp/examples -type f | grep '.js$' | while read line; do
    babel "$line" > "$line.temp"
    mv "$line.temp" "$line"
done

# Build website documents
tar -cvf website.tar temp

# Cleanup
rm -r temp
